version: "3.9"

services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:3000

  server:
    image: server
    build: ./server
    volumes:
      - ./assets:/var/assets
      - ./server:/var/server

  client:
    image: client
    build: ./client
    volumes:
      - ./client:/var/client

  
